hf_training_args:
  do_train: True
  do_eval: True

  max_steps: 1_000_000
  optim: "adamw_torch"
  learning_rate: 0.00002
  warmup_steps: 1000

  per_device_train_batch_size: 2
  gradient_accumulation_steps: 16
  per_device_eval_batch_size: 1
  eval_accumulation_steps: 8

  dataloader_num_workers: 16
  dataloader_pin_memory: True
  dataloader_drop_last: False

  logging_steps: 1
  report_to: "wandb"
  remove_unused_columns: False # NEVER TOUCH THIS

  # TODO check if this makes training faster (or use less memory) in our setup
  fp16: True

  metric_for_best_model: "audiocaps/spider"
  greater_is_better: True

  load_best_model_at_end: True
  predict_with_generate: True # NEVER TOUCH THIS
  generation_num_beams: 1
  generation_max_length: 80
  evaluation_strategy: "steps"
  eval_steps: 900

  save_strategy: "steps"
  save_steps: 900
  save_total_limit: 5


architecture:
  name: "openai/whisper-large-v2"
  use_pretrained_whisper_encoder: True
  use_pretrained_whisper_decoder: True

early_stopping:
  should_early_stop: False
  early_stopping_patience: null
  early_stopping_threshold: null

logging:
  log_preds_every_n_steps: 300
  # these are per dataset
  log_preds_num_train: 4
  log_preds_num_valid: 10

dataset_mix:
  weights: 
    clotho: 0.0
    audioset: 3.0
    audiocaps: 1.0
  limit_val_split:
    clotho: null
    audioset: 200
    audiocaps: null
